name = "GregTech Tier Zero"
author = "Iterable"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b23086a460e7ce96248c5ebfc620dd6c2a54f45f18d4f5b49be99f447c490b5"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
