name = "GregTech: Tier Zero"
author = "Iterable"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04e7e800db24ed42af660e5f249a7e4023fbfc45afcc1330a799c2b6b75192db"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
