name = "GregTech Tier Zero"
author = "Iterable"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6750635f011b3cf014c92ea1bfc85b5b456737d58a71156dbebc5ac997ef75f1"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
