#KubeJS Client Properties
#Sun Sep 06 02:57:33 EDT 2026
backgroundColor=08140C
barBorderColor=1A6B34
exportAtlases=false
menuBackgroundBrightness=64
disableRecipeBook=false
title=GregTech: Tier Zero
barColor=33FF66
overrideColors=false
fmlLogColor=A8FFC0
showTagNames=false
fmlMemoryColor=B6FF3B
menuBackgroundScale=32.0
blurScaledPackIcon=true
menuInnerBackgroundBrightness=32